/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// ======== ВАЖНО: ЭТИ ИМПОРТЫ ДОБАВЬ! ========
import { Configuration } from './configuration';
import { AdvertsApi } from './api/adverts-api';
import { UsersApi } from './api/users-api';
import { CategoriesApi } from './api/categories-api';
import { LikesApi } from './api/likes-api';
import { DealsApi } from './api/deals-api';

// ======== ОРИГИНАЛЬНЫЕ ЭКСПОРТЫ (оставь как есть) ========
export * from './api/adverts-api';
export * from './api/categories-api';
export * from './api/deals-api';
export * from './api/likes-api';
export * from './api/users-api';

// ======== ТВОЙ КОД (исправленный) ========

// Базовый URL вашего бэкенда FastAPI
// МЕНЯЙ ЗДЕСЬ ЕСЛИ НУЖНО ДРУГОЙ АДРЕС!
const API_BASE_URL = 'http://localhost:8000';

// Получаем токен из localStorage
const getAuthToken = (): string | null => {
  return localStorage.getItem('auth_token');
};

// Создаем базовую конфигурацию
const createConfiguration = (): Configuration => {
  const token = getAuthToken();

  return new Configuration({
    basePath: API_BASE_URL, // ← ВОТ СЮДА ПЕРЕДАЕТСЯ АДРЕС!
    accessToken: token || undefined,
    baseOptions: {
      timeout: 10000, // 10 секунд таймаут
      headers: {
        'Content-Type': 'application/json',
      },
    },
  });
};

// Создаем конфигурацию
const config = createConfiguration();

// Создаем готовые API клиенты
export const advertsApi = new AdvertsApi(config);
export const usersApi = new UsersApi(config);
export const categoriesApi = new CategoriesApi(config);
export const likesApi = new LikesApi(config);
export const dealsApi = new DealsApi(config);

// Функция для обновления токена (после логина)
export const updateAuthToken = (token: string) => {
  localStorage.setItem('auth_token', token);

  // Создаем новую конфигурацию с токеном
  const newConfig = new Configuration({
    ...config,
    accessToken: token,
  });

  // Обновляем конфигурацию у всех API клиентов
  advertsApi.configuration = newConfig;
  usersApi.configuration = newConfig;
  categoriesApi.configuration = newConfig;
  likesApi.configuration = newConfig;
  dealsApi.configuration = newConfig;
};

// Функция для удаления токена (логаут)
export const clearAuthToken = () => {
  localStorage.removeItem('auth_token');

  const newConfig = new Configuration({
    ...config,
    accessToken: undefined,
  });

  advertsApi.configuration = newConfig;
  usersApi.configuration = newConfig;
  categoriesApi.configuration = newConfig;
  likesApi.configuration = newConfig;
  dealsApi.configuration = newConfig;
};