/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AdvertCreateDTO } from '../models';
// @ts-ignore
import type { AdvertListResponseDTO } from '../models';
// @ts-ignore
import type { AdvertResponseDTO } from '../models';
// @ts-ignore
import type { AdvertSearchRequestDTO } from '../models';
// @ts-ignore
import type { AdvertUpdateFullDTO } from '../models';
// @ts-ignore
import type { AdvertUpdatePartialDTO } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * AdvertsApi - axios parameter creator
 */
export const AdvertsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create Advert
         * @param {AdvertCreateDTO} advertCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAdvertApiV1AdvertsPost: async (advertCreateDTO: AdvertCreateDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'advertCreateDTO' is not null or undefined
            assertParamExists('createAdvertApiV1AdvertsPost', 'advertCreateDTO', advertCreateDTO)
            const localVarPath = `/api/v1/adverts/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(advertCreateDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete advert - только для владельца
         * @summary Delete Advert
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAdvertApiV1AdvertsAdvertIdDelete: async (advertId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'advertId' is not null or undefined
            assertParamExists('deleteAdvertApiV1AdvertsAdvertIdDelete', 'advertId', advertId)
            const localVarPath = `/api/v1/adverts/{advert_id}`
                .replace(`{${"advert_id"}}`, encodeURIComponent(String(advertId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get advert by ID
         * @summary Get Advert
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdvertApiV1AdvertsAdvertIdGet: async (advertId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'advertId' is not null or undefined
            assertParamExists('getAdvertApiV1AdvertsAdvertIdGet', 'advertId', advertId)
            const localVarPath = `/api/v1/adverts/{advert_id}`
                .replace(`{${"advert_id"}}`, encodeURIComponent(String(advertId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all adverts
         * @summary Get All Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAdvertsApiV1AdvertsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/adverts/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all adverts in deals
         * @summary Get In Deals Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInDealsAdvertsApiV1AdvertsDealsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/adverts/deals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all adverts liked
         * @summary Get Liked Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedAdvertsApiV1AdvertsLikedGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/adverts/liked`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all adverts my created
         * @summary Get My Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyAdvertsApiV1AdvertsCreatedGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/adverts/created`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get all adverts
         * @summary Get Search Adverts
         * @param {AdvertSearchRequestDTO} advertSearchRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSearchAdvertsApiV1AdvertsSearchPost: async (advertSearchRequestDTO: AdvertSearchRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'advertSearchRequestDTO' is not null or undefined
            assertParamExists('getSearchAdvertsApiV1AdvertsSearchPost', 'advertSearchRequestDTO', advertSearchRequestDTO)
            const localVarPath = `/api/v1/adverts/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(advertSearchRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update advert (full update) - только для владельца
         * @summary Update Advert Full
         * @param {string} advertId 
         * @param {AdvertUpdateFullDTO} advertUpdateFullDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdvertFullApiV1AdvertsAdvertIdPut: async (advertId: string, advertUpdateFullDTO: AdvertUpdateFullDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'advertId' is not null or undefined
            assertParamExists('updateAdvertFullApiV1AdvertsAdvertIdPut', 'advertId', advertId)
            // verify required parameter 'advertUpdateFullDTO' is not null or undefined
            assertParamExists('updateAdvertFullApiV1AdvertsAdvertIdPut', 'advertUpdateFullDTO', advertUpdateFullDTO)
            const localVarPath = `/api/v1/adverts/{advert_id}`
                .replace(`{${"advert_id"}}`, encodeURIComponent(String(advertId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(advertUpdateFullDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update advert (partial update) - только для владельца
         * @summary Update Advert Partial
         * @param {string} advertId 
         * @param {AdvertUpdatePartialDTO} advertUpdatePartialDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdvertPartialApiV1AdvertsAdvertIdPatch: async (advertId: string, advertUpdatePartialDTO: AdvertUpdatePartialDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'advertId' is not null or undefined
            assertParamExists('updateAdvertPartialApiV1AdvertsAdvertIdPatch', 'advertId', advertId)
            // verify required parameter 'advertUpdatePartialDTO' is not null or undefined
            assertParamExists('updateAdvertPartialApiV1AdvertsAdvertIdPatch', 'advertUpdatePartialDTO', advertUpdatePartialDTO)
            const localVarPath = `/api/v1/adverts/{advert_id}`
                .replace(`{${"advert_id"}}`, encodeURIComponent(String(advertId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(advertUpdatePartialDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdvertsApi - functional programming interface
 */
export const AdvertsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdvertsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create Advert
         * @param {AdvertCreateDTO} advertCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAdvertApiV1AdvertsPost(advertCreateDTO: AdvertCreateDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAdvertApiV1AdvertsPost(advertCreateDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.createAdvertApiV1AdvertsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete advert - только для владельца
         * @summary Delete Advert
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteAdvertApiV1AdvertsAdvertIdDelete(advertId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteAdvertApiV1AdvertsAdvertIdDelete(advertId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.deleteAdvertApiV1AdvertsAdvertIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get advert by ID
         * @summary Get Advert
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAdvertApiV1AdvertsAdvertIdGet(advertId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAdvertApiV1AdvertsAdvertIdGet(advertId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.getAdvertApiV1AdvertsAdvertIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all adverts
         * @summary Get All Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllAdvertsApiV1AdvertsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertListResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllAdvertsApiV1AdvertsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.getAllAdvertsApiV1AdvertsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all adverts in deals
         * @summary Get In Deals Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInDealsAdvertsApiV1AdvertsDealsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertListResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInDealsAdvertsApiV1AdvertsDealsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.getInDealsAdvertsApiV1AdvertsDealsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all adverts liked
         * @summary Get Liked Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLikedAdvertsApiV1AdvertsLikedGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertListResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLikedAdvertsApiV1AdvertsLikedGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.getLikedAdvertsApiV1AdvertsLikedGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all adverts my created
         * @summary Get My Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyAdvertsApiV1AdvertsCreatedGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertListResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyAdvertsApiV1AdvertsCreatedGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.getMyAdvertsApiV1AdvertsCreatedGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get all adverts
         * @summary Get Search Adverts
         * @param {AdvertSearchRequestDTO} advertSearchRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSearchAdvertsApiV1AdvertsSearchPost(advertSearchRequestDTO: AdvertSearchRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertListResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSearchAdvertsApiV1AdvertsSearchPost(advertSearchRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.getSearchAdvertsApiV1AdvertsSearchPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update advert (full update) - только для владельца
         * @summary Update Advert Full
         * @param {string} advertId 
         * @param {AdvertUpdateFullDTO} advertUpdateFullDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAdvertFullApiV1AdvertsAdvertIdPut(advertId: string, advertUpdateFullDTO: AdvertUpdateFullDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAdvertFullApiV1AdvertsAdvertIdPut(advertId, advertUpdateFullDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.updateAdvertFullApiV1AdvertsAdvertIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update advert (partial update) - только для владельца
         * @summary Update Advert Partial
         * @param {string} advertId 
         * @param {AdvertUpdatePartialDTO} advertUpdatePartialDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAdvertPartialApiV1AdvertsAdvertIdPatch(advertId: string, advertUpdatePartialDTO: AdvertUpdatePartialDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AdvertResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAdvertPartialApiV1AdvertsAdvertIdPatch(advertId, advertUpdatePartialDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdvertsApi.updateAdvertPartialApiV1AdvertsAdvertIdPatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdvertsApi - factory interface
 */
export const AdvertsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdvertsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create Advert
         * @param {AdvertCreateDTO} advertCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAdvertApiV1AdvertsPost(advertCreateDTO: AdvertCreateDTO, options?: RawAxiosRequestConfig): AxiosPromise<AdvertResponseDTO> {
            return localVarFp.createAdvertApiV1AdvertsPost(advertCreateDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete advert - только для владельца
         * @summary Delete Advert
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteAdvertApiV1AdvertsAdvertIdDelete(advertId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteAdvertApiV1AdvertsAdvertIdDelete(advertId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get advert by ID
         * @summary Get Advert
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAdvertApiV1AdvertsAdvertIdGet(advertId: string, options?: RawAxiosRequestConfig): AxiosPromise<AdvertResponseDTO> {
            return localVarFp.getAdvertApiV1AdvertsAdvertIdGet(advertId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get all adverts
         * @summary Get All Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllAdvertsApiV1AdvertsGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO> {
            return localVarFp.getAllAdvertsApiV1AdvertsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get all adverts in deals
         * @summary Get In Deals Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInDealsAdvertsApiV1AdvertsDealsGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO> {
            return localVarFp.getInDealsAdvertsApiV1AdvertsDealsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get all adverts liked
         * @summary Get Liked Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedAdvertsApiV1AdvertsLikedGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO> {
            return localVarFp.getLikedAdvertsApiV1AdvertsLikedGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get all adverts my created
         * @summary Get My Adverts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyAdvertsApiV1AdvertsCreatedGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO> {
            return localVarFp.getMyAdvertsApiV1AdvertsCreatedGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get all adverts
         * @summary Get Search Adverts
         * @param {AdvertSearchRequestDTO} advertSearchRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSearchAdvertsApiV1AdvertsSearchPost(advertSearchRequestDTO: AdvertSearchRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO> {
            return localVarFp.getSearchAdvertsApiV1AdvertsSearchPost(advertSearchRequestDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Update advert (full update) - только для владельца
         * @summary Update Advert Full
         * @param {string} advertId 
         * @param {AdvertUpdateFullDTO} advertUpdateFullDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdvertFullApiV1AdvertsAdvertIdPut(advertId: string, advertUpdateFullDTO: AdvertUpdateFullDTO, options?: RawAxiosRequestConfig): AxiosPromise<AdvertResponseDTO> {
            return localVarFp.updateAdvertFullApiV1AdvertsAdvertIdPut(advertId, advertUpdateFullDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Update advert (partial update) - только для владельца
         * @summary Update Advert Partial
         * @param {string} advertId 
         * @param {AdvertUpdatePartialDTO} advertUpdatePartialDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAdvertPartialApiV1AdvertsAdvertIdPatch(advertId: string, advertUpdatePartialDTO: AdvertUpdatePartialDTO, options?: RawAxiosRequestConfig): AxiosPromise<AdvertResponseDTO> {
            return localVarFp.updateAdvertPartialApiV1AdvertsAdvertIdPatch(advertId, advertUpdatePartialDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdvertsApi - interface
 */
export interface AdvertsApiInterface {
    /**
     * 
     * @summary Create Advert
     * @param {AdvertCreateDTO} advertCreateDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createAdvertApiV1AdvertsPost(advertCreateDTO: AdvertCreateDTO, options?: RawAxiosRequestConfig): AxiosPromise<AdvertResponseDTO>;

    /**
     * Delete advert - только для владельца
     * @summary Delete Advert
     * @param {string} advertId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteAdvertApiV1AdvertsAdvertIdDelete(advertId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get advert by ID
     * @summary Get Advert
     * @param {string} advertId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAdvertApiV1AdvertsAdvertIdGet(advertId: string, options?: RawAxiosRequestConfig): AxiosPromise<AdvertResponseDTO>;

    /**
     * Get all adverts
     * @summary Get All Adverts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllAdvertsApiV1AdvertsGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO>;

    /**
     * Get all adverts in deals
     * @summary Get In Deals Adverts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getInDealsAdvertsApiV1AdvertsDealsGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO>;

    /**
     * Get all adverts liked
     * @summary Get Liked Adverts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLikedAdvertsApiV1AdvertsLikedGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO>;

    /**
     * Get all adverts my created
     * @summary Get My Adverts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMyAdvertsApiV1AdvertsCreatedGet(options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO>;

    /**
     * Get all adverts
     * @summary Get Search Adverts
     * @param {AdvertSearchRequestDTO} advertSearchRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSearchAdvertsApiV1AdvertsSearchPost(advertSearchRequestDTO: AdvertSearchRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<AdvertListResponseDTO>;

    /**
     * Update advert (full update) - только для владельца
     * @summary Update Advert Full
     * @param {string} advertId 
     * @param {AdvertUpdateFullDTO} advertUpdateFullDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAdvertFullApiV1AdvertsAdvertIdPut(advertId: string, advertUpdateFullDTO: AdvertUpdateFullDTO, options?: RawAxiosRequestConfig): AxiosPromise<AdvertResponseDTO>;

    /**
     * Update advert (partial update) - только для владельца
     * @summary Update Advert Partial
     * @param {string} advertId 
     * @param {AdvertUpdatePartialDTO} advertUpdatePartialDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateAdvertPartialApiV1AdvertsAdvertIdPatch(advertId: string, advertUpdatePartialDTO: AdvertUpdatePartialDTO, options?: RawAxiosRequestConfig): AxiosPromise<AdvertResponseDTO>;

}

/**
 * AdvertsApi - object-oriented interface
 */
export class AdvertsApi extends BaseAPI implements AdvertsApiInterface {
    /**
     * 
     * @summary Create Advert
     * @param {AdvertCreateDTO} advertCreateDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createAdvertApiV1AdvertsPost(advertCreateDTO: AdvertCreateDTO, options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).createAdvertApiV1AdvertsPost(advertCreateDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete advert - только для владельца
     * @summary Delete Advert
     * @param {string} advertId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteAdvertApiV1AdvertsAdvertIdDelete(advertId: string, options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).deleteAdvertApiV1AdvertsAdvertIdDelete(advertId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get advert by ID
     * @summary Get Advert
     * @param {string} advertId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAdvertApiV1AdvertsAdvertIdGet(advertId: string, options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).getAdvertApiV1AdvertsAdvertIdGet(advertId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all adverts
     * @summary Get All Adverts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllAdvertsApiV1AdvertsGet(options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).getAllAdvertsApiV1AdvertsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all adverts in deals
     * @summary Get In Deals Adverts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getInDealsAdvertsApiV1AdvertsDealsGet(options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).getInDealsAdvertsApiV1AdvertsDealsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all adverts liked
     * @summary Get Liked Adverts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLikedAdvertsApiV1AdvertsLikedGet(options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).getLikedAdvertsApiV1AdvertsLikedGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all adverts my created
     * @summary Get My Adverts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMyAdvertsApiV1AdvertsCreatedGet(options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).getMyAdvertsApiV1AdvertsCreatedGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get all adverts
     * @summary Get Search Adverts
     * @param {AdvertSearchRequestDTO} advertSearchRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getSearchAdvertsApiV1AdvertsSearchPost(advertSearchRequestDTO: AdvertSearchRequestDTO, options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).getSearchAdvertsApiV1AdvertsSearchPost(advertSearchRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update advert (full update) - только для владельца
     * @summary Update Advert Full
     * @param {string} advertId 
     * @param {AdvertUpdateFullDTO} advertUpdateFullDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateAdvertFullApiV1AdvertsAdvertIdPut(advertId: string, advertUpdateFullDTO: AdvertUpdateFullDTO, options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).updateAdvertFullApiV1AdvertsAdvertIdPut(advertId, advertUpdateFullDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update advert (partial update) - только для владельца
     * @summary Update Advert Partial
     * @param {string} advertId 
     * @param {AdvertUpdatePartialDTO} advertUpdatePartialDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateAdvertPartialApiV1AdvertsAdvertIdPatch(advertId: string, advertUpdatePartialDTO: AdvertUpdatePartialDTO, options?: RawAxiosRequestConfig) {
        return AdvertsApiFp(this.configuration).updateAdvertPartialApiV1AdvertsAdvertIdPatch(advertId, advertUpdatePartialDTO, options).then((request) => request(this.axios, this.basePath));
    }
}

