/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CategoryListResponseDTO } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * CategoriesApi - axios parameter creator
 */
export const CategoriesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all categories
         * @summary Get All Categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCategoriesApiV1CategoriesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/categories/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get category by ID
         * @summary Get Category
         * @param {string} categoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoryApiV1CategoriesCategoryIdGet: async (categoryId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'categoryId' is not null or undefined
            assertParamExists('getCategoryApiV1CategoriesCategoryIdGet', 'categoryId', categoryId)
            const localVarPath = `/api/v1/categories/{category_id}`
                .replace(`{${"category_id"}}`, encodeURIComponent(String(categoryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CategoriesApi - functional programming interface
 */
export const CategoriesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CategoriesApiAxiosParamCreator(configuration)
    return {
        /**
         * Get all categories
         * @summary Get All Categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllCategoriesApiV1CategoriesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CategoryListResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllCategoriesApiV1CategoriesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CategoriesApi.getAllCategoriesApiV1CategoriesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get category by ID
         * @summary Get Category
         * @param {string} categoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCategoryApiV1CategoriesCategoryIdGet(categoryId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCategoryApiV1CategoriesCategoryIdGet(categoryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CategoriesApi.getCategoryApiV1CategoriesCategoryIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CategoriesApi - factory interface
 */
export const CategoriesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CategoriesApiFp(configuration)
    return {
        /**
         * Get all categories
         * @summary Get All Categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllCategoriesApiV1CategoriesGet(options?: RawAxiosRequestConfig): AxiosPromise<CategoryListResponseDTO> {
            return localVarFp.getAllCategoriesApiV1CategoriesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get category by ID
         * @summary Get Category
         * @param {string} categoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCategoryApiV1CategoriesCategoryIdGet(categoryId: string, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getCategoryApiV1CategoriesCategoryIdGet(categoryId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CategoriesApi - interface
 */
export interface CategoriesApiInterface {
    /**
     * Get all categories
     * @summary Get All Categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAllCategoriesApiV1CategoriesGet(options?: RawAxiosRequestConfig): AxiosPromise<CategoryListResponseDTO>;

    /**
     * Get category by ID
     * @summary Get Category
     * @param {string} categoryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCategoryApiV1CategoriesCategoryIdGet(categoryId: string, options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * CategoriesApi - object-oriented interface
 */
export class CategoriesApi extends BaseAPI implements CategoriesApiInterface {
    /**
     * Get all categories
     * @summary Get All Categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAllCategoriesApiV1CategoriesGet(options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getAllCategoriesApiV1CategoriesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get category by ID
     * @summary Get Category
     * @param {string} categoryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCategoryApiV1CategoriesCategoryIdGet(categoryId: string, options?: RawAxiosRequestConfig) {
        return CategoriesApiFp(this.configuration).getCategoryApiV1CategoriesCategoryIdGet(categoryId, options).then((request) => request(this.axios, this.basePath));
    }
}

