/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DealCreateRequestDTO } from '../models';
// @ts-ignore
import type { DealResponseDTO } from '../models';
// @ts-ignore
import type { HTTPValidationError } from '../models';
/**
 * DealsApi - axios parameter creator
 */
export const DealsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a deal
         * @summary Create Deal
         * @param {DealCreateRequestDTO} dealCreateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDealApiV1DealsPost: async (dealCreateRequestDTO: DealCreateRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'dealCreateRequestDTO' is not null or undefined
            assertParamExists('createDealApiV1DealsPost', 'dealCreateRequestDTO', dealCreateRequestDTO)
            const localVarPath = `/api/v1/deals/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dealCreateRequestDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DealsApi - functional programming interface
 */
export const DealsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DealsApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a deal
         * @summary Create Deal
         * @param {DealCreateRequestDTO} dealCreateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDealApiV1DealsPost(dealCreateRequestDTO: DealCreateRequestDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DealResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDealApiV1DealsPost(dealCreateRequestDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DealsApi.createDealApiV1DealsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DealsApi - factory interface
 */
export const DealsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DealsApiFp(configuration)
    return {
        /**
         * Create a deal
         * @summary Create Deal
         * @param {DealCreateRequestDTO} dealCreateRequestDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDealApiV1DealsPost(dealCreateRequestDTO: DealCreateRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<DealResponseDTO> {
            return localVarFp.createDealApiV1DealsPost(dealCreateRequestDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DealsApi - interface
 */
export interface DealsApiInterface {
    /**
     * Create a deal
     * @summary Create Deal
     * @param {DealCreateRequestDTO} dealCreateRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDealApiV1DealsPost(dealCreateRequestDTO: DealCreateRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<DealResponseDTO>;

}

/**
 * DealsApi - object-oriented interface
 */
export class DealsApi extends BaseAPI implements DealsApiInterface {
    /**
     * Create a deal
     * @summary Create Deal
     * @param {DealCreateRequestDTO} dealCreateRequestDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDealApiV1DealsPost(dealCreateRequestDTO: DealCreateRequestDTO, options?: RawAxiosRequestConfig) {
        return DealsApiFp(this.configuration).createDealApiV1DealsPost(dealCreateRequestDTO, options).then((request) => request(this.axios, this.basePath));
    }
}

