/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { HTTPValidationError } from '../models';
// @ts-ignore
import type { LikeResponseDTO } from '../models';
/**
 * LikesApi - axios parameter creator
 */
export const LikesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Like an advert
         * @summary Add Like
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLikeApiV1AdvertsAdvertIdLikesPost: async (advertId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'advertId' is not null or undefined
            assertParamExists('addLikeApiV1AdvertsAdvertIdLikesPost', 'advertId', advertId)
            const localVarPath = `/api/v1/adverts/{advert_id}/likes`
                .replace(`{${"advert_id"}}`, encodeURIComponent(String(advertId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove like from advert
         * @summary Remove Like
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeLikeApiV1AdvertsAdvertIdLikesDelete: async (advertId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'advertId' is not null or undefined
            assertParamExists('removeLikeApiV1AdvertsAdvertIdLikesDelete', 'advertId', advertId)
            const localVarPath = `/api/v1/adverts/{advert_id}/likes`
                .replace(`{${"advert_id"}}`, encodeURIComponent(String(advertId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LikesApi - functional programming interface
 */
export const LikesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LikesApiAxiosParamCreator(configuration)
    return {
        /**
         * Like an advert
         * @summary Add Like
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLikeApiV1AdvertsAdvertIdLikesPost(advertId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LikeResponseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLikeApiV1AdvertsAdvertIdLikesPost(advertId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LikesApi.addLikeApiV1AdvertsAdvertIdLikesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove like from advert
         * @summary Remove Like
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeLikeApiV1AdvertsAdvertIdLikesDelete(advertId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeLikeApiV1AdvertsAdvertIdLikesDelete(advertId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LikesApi.removeLikeApiV1AdvertsAdvertIdLikesDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LikesApi - factory interface
 */
export const LikesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LikesApiFp(configuration)
    return {
        /**
         * Like an advert
         * @summary Add Like
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLikeApiV1AdvertsAdvertIdLikesPost(advertId: string, options?: RawAxiosRequestConfig): AxiosPromise<LikeResponseDTO> {
            return localVarFp.addLikeApiV1AdvertsAdvertIdLikesPost(advertId, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove like from advert
         * @summary Remove Like
         * @param {string} advertId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeLikeApiV1AdvertsAdvertIdLikesDelete(advertId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeLikeApiV1AdvertsAdvertIdLikesDelete(advertId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LikesApi - interface
 */
export interface LikesApiInterface {
    /**
     * Like an advert
     * @summary Add Like
     * @param {string} advertId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    addLikeApiV1AdvertsAdvertIdLikesPost(advertId: string, options?: RawAxiosRequestConfig): AxiosPromise<LikeResponseDTO>;

    /**
     * Remove like from advert
     * @summary Remove Like
     * @param {string} advertId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeLikeApiV1AdvertsAdvertIdLikesDelete(advertId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * LikesApi - object-oriented interface
 */
export class LikesApi extends BaseAPI implements LikesApiInterface {
    /**
     * Like an advert
     * @summary Add Like
     * @param {string} advertId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public addLikeApiV1AdvertsAdvertIdLikesPost(advertId: string, options?: RawAxiosRequestConfig) {
        return LikesApiFp(this.configuration).addLikeApiV1AdvertsAdvertIdLikesPost(advertId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove like from advert
     * @summary Remove Like
     * @param {string} advertId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public removeLikeApiV1AdvertsAdvertIdLikesDelete(advertId: string, options?: RawAxiosRequestConfig) {
        return LikesApiFp(this.configuration).removeLikeApiV1AdvertsAdvertIdLikesDelete(advertId, options).then((request) => request(this.axios, this.basePath));
    }
}

