/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AdvertResponseDTO {
    'id': string;
    'content': string;
    'description': string;
    'price': number;
    'id_category': string;
    'id_seller': string;
    'date_created': string;
    'category_name'?: string | null;
    'seller_name'?: string | null;
    'is_created'?: boolean | null;
    'is_liked'?: boolean | null;
    'is_bought'?: boolean | null;
    'is_bought_by_current'?: boolean | null;
}

